### ISSUE TITLE
About the Naive2 function

### ISSUE THREAD

**Issue by chendiva** [kdgutier/esrnn_torch#12]
Hi there, 
   Are you able to show an example about how to use Naive2 prediction ( The class you have for ESRNN). I am wondering what is the h in the predict function. Since I am trying to input an array, but it doesn't seem to work. Thanks!

**Comment by kdgutier** [comment]
Naive2 implementation is available here https://github.com/kdgutier/esrnn_torch/blob/master/ESRNN/utils_evaluation.py
