### ISSUE TITLE
problem when executing the example of m4 (tensor problem)

### ISSUE THREAD

**Issue by ramdhan1989** [kdgutier/esrnn_torch#14]
Hi,
I got error below : 
RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cpu and hidden tensor at cuda:0

when executing the example of m4 : 
`X_train_df, y_train_df, X_test_df, y_test_df = prepare_m4_data(dataset_name='Yearly',
                                                               directory = './data',
                                                               num_obs=1000)

# Instantiate model
model = ESRNN(max_epochs=25, freq_of_test=5, batch_size=4, learning_rate=1e-4,
              per_series_lr_multip=0.8, lr_scheduler_step_size=10,
              lr_decay=0.1, gradient_clipping_threshold=50,
              rnn_weight_decay=0.0, level_variability_penalty=100,
              testing_percentile=50, training_percentile=50,
              ensemble=False, max_periods=25, seasonality=[],
              input_size=4, output_size=6,
              cell_type='LSTM', state_hsize=40,
              dilations=[[1], [6]], add_nl_layer=False,
              random_seed=1, device='cpu')

# Fit model
# If y_test_df is provided the model
# will evaluate predictions on
# this set every freq_test epochs
model.fit(X_train_df, y_train_df, X_test_df, y_test_df)

# Predict on test set
y_hat_df = model.predict(X_test_df)

# Evaluate predictions
final_owa, final_mase, final_smape = evaluate_prediction_owa(y_hat_df, y_train_df,
                                                             X_test_df, y_test_df,
                                                             naive2_seasonality=1)`

full eror message : 
`Infered frequency: D
=============== Training ESRNN  ===============

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-7135926c2a2e> in <module>
     19 # will evaluate predictions on
     20 # this set every freq_test epochs
---> 21 model.fit(X_train_df, y_train_df, X_test_df, y_test_df)
     22 
     23 # Predict on test set

~\Anaconda3\envs\nlp\lib\site-packages\ESRNN\ESRNN.py in fit(self, X_df, y_df, X_test_df, y_test_df, y_hat_benchmark, warm_start, shuffle, verbose)
    366     self._fitted = True
    367     self.train(dataloader=self.train_dataloader, max_epochs=self.mc.max_epochs,
--> 368                warm_start=warm_start, shuffle=shuffle, verbose=verbose)
    369 
    370   def instantiate_esrnn(self, exogenous_size, n_series):

~\Anaconda3\envs\nlp\lib\site-packages\ESRNN\ESRNN.py in train(self, dataloader, max_epochs, warm_start, shuffle, verbose)
    184 
    185         batch = dataloader.get_batch()
--> 186         windows_y, windows_y_hat, levels = self.esrnn(batch)
    187 
    188         # Pinball loss on normalized values

~\Anaconda3\envs\nlp\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~\Anaconda3\envs\nlp\lib\site-packages\ESRNN\utils\ESRNN.py in forward(self, ts_object)
    274 
    275     # RNN Forward
--> 276     windows_y_hat = self.rnn(windows_y_hat)
    277 
    278     return windows_y, windows_y_hat, levels

~\Anaconda3\envs\nlp\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~\Anaconda3\envs\nlp\lib\site-packages\ESRNN\utils\ESRNN.py in forward(self, input_data)
    249     for layer_num in range(len(self.rnn_stack)):
    250       residual = input_data
--> 251       output, _ = self.rnn_stack[layer_num](input_data)
    252       if layer_num > 0:
    253         output += residual

~\Anaconda3\envs\nlp\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~\Anaconda3\envs\nlp\lib\site-packages\ESRNN\utils\DRNN.py in forward(self, inputs, hidden)
    181         for i, (cell, dilation) in enumerate(zip(self.cells, self.dilations)):
    182             if hidden is None:
--> 183                 inputs, _ = self.drnn_layer(cell, inputs, dilation)
    184             else:
    185                 inputs, hidden[i] = self.drnn_layer(cell, inputs, dilation, hidden[i])

~\Anaconda3\envs\nlp\lib\site-packages\ESRNN\utils\DRNN.py in drnn_layer(self, cell, inputs, rate, hidden)
    201 
    202         if hidden is None:
--> 203             dilated_outputs, hidden = self._apply_cell(dilated_inputs, cell, batch_size, rate, hidden_size)
    204         else:
    205             hidden = self._prepare_inputs(hidden, rate)

~\Anaconda3\envs\nlp\lib\site-packages\ESRNN\utils\DRNN.py in _apply_cell(self, dilated_inputs, cell, batch_size, rate, hidden_size, hidden)
    220                 hidden = self.init_hidden(batch_size * rate, hidden_size).unsqueeze(0)
    221 
--> 222         dilated_outputs, hidden = cell(dilated_inputs, hidden) # compatibility hack
    223 
    224         return dilated_outputs, hidden

~\Anaconda3\envs\nlp\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~\Anaconda3\envs\nlp\lib\site-packages\torch\nn\modules\rnn.py in forward(self, input, hx)
    568         if batch_sizes is None:
    569             result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
--> 570                               self.dropout, self.training, self.bidirectional, self.batch_first)
    571         else:
    572             result = _VF.lstm(input, batch_sizes, hx, self._flat_weights, self.bias,

RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cpu and hidden tensor at cuda:0`

**Comment by ramdhan1989** [comment]
Solved. set device to cuda

**Comment by kdgutier** [comment]
What is your pytorch installation?
Are you trying to run it on cpu or gpu.
Try setting the device='cuda' and see if that helps.

**Comment by ramdhan1989** [comment]
thanks, it works by setting device to cuda
