### ISSUE TITLE
about exogenous variable

### ISSUE THREAD

**Issue by ramdhan1989** [kdgutier/esrnn_torch#15]
Hi, I would like to try for my own dataset. I have some questions regarding exogenous variable. 
does the method allow multiple exogenous variable ? does the method use future exogenous variable to predict future target ? If yes, how to configure my dataset for my case where exogenous variable is not available for forecasting?

thank you

**Comment by kdgutier** [comment]
This is pending work, so far the Iterator class in the train method is only suited for a single categorical exogenous variable that can vary over time. We are working for a next Iterator version to use pytorch dataloaders and include any number of exogenous.
The ESRNN model uses the categorical exogenous variable that may change over time, and appends it in the RNN input, just like in the original implementation, for a better explanation https://www.sciencedirect.com/science/article/pii/S0169207019301153.

**Comment by ramdhan1989** [comment]
thanks for your information. my intention was to add continues exogenous variable. There is group of id as well in my dataset. So, for now, I would like to try using that group for categorical exogenous which I certainly will have that information as future information for forecasting.

thanks a lot

**Comment by kdgutier** [comment]
In the meantime as a work around if you want to us the continuous exogenous variable, I recommend you to discretize it into intervals. You may continue the hack and use interaction of interval x group careful with the levels being too big because that interaction will scale quadratically.
