### ISSUE TITLE
Negative or very small positive values produce nan values of loss and metric during training 

### ISSUE THREAD

**Issue by ramdhan1989** [kdgutier/esrnn_torch#18]
Hi,
I am struggle with nan values of loss and metric during training. several things that has been tried to solve it but still doesn't work : 
1. change range of target (negative - positive) into 0-1 using minmaxscaler
2. exclude series with constant values throughout the time
3. change unique_id and x from integer type to str type

do you have any idea to solve it ?

thanks

**Comment by kdgutier** [comment]
Multiplicative regression models like ESRNN estimate the parameters on log transformed data, if one uses negative values the logarithms will fail. 
An advisable data preprocessing before taking it into the ESRNN model is to translate (to make positive) and then transform (scaling).
If your data is already preprocessed to be positive and scaled, then I would check the learning rates in case the optimization procedure is diverging. Hope this solves the problem.

**Comment by ramdhan1989** [comment]
thanks, it works ! the data is translated to positive by adding the value with absolute of min value and add 10. so the value is between 10 and (max + absolute of min). what do you think ? do you have better alternative ?

please advice,
thanks

**Comment by kdgutier** [comment]
That is what I would do, good that it works.
