### ISSUE TITLE
Missing values when multivariate

### ISSUE THREAD

**Issue by CoteDave** [kdgutier/esrnn_torch#21]
When using multiple timeseries ID, there seem to be missing values after the predict:

![image](https://user-images.githubusercontent.com/49559881/97761262-a0087180-1adb-11eb-8d34-a964a851653b.png)

**Comment by CoteDave** [comment]
Resolved!

**Comment by kdgutier** [comment]
Hi @CoteDave, something similar happened before to a user, the reason behind it was a problem with the date stamps generated in pandas for the prediction merge into the final data frame.
Another time it was a mismatch between expected output_sizes of the test and the output_size of the model. 
What was the problem for you?

**Comment by CoteDave** [comment]
Sure! I was thinking that the model automaticly fills all the dates in the data given to the predict method. Unfortunatly, I discovered the "outputs" hyper-parameter that was set to 3... so even if my predict data has 12 dates in it, it only returned 3 predictions. My bad!
