### ISSUE TITLE
Understanding unique_id and "x" category

### ISSUE THREAD

**Issue by CoteDave** [kdgutier/esrnn_torch#23]
Hi,

When forecasting multiple Time-series at a time, I was wondering whats the mechanics  between the "unique_id" and "x" category feeded to the ESRNN ?

Does the model learns each Time series independently of each others by unique_id and learns interactions between Time series with same unique_id and different "x" categories values ? 

Can we use the "x" to learn hierarchies ? For example if we decompose the same Time serie into 3 others Time series (for example using 3 different data filters), the unique_id is the same for the 3 (same original Time series) but different categories (filter1, filter2, filter3), soo each dates are multiplied 3 Times here for the same unique_id, one by category. 

Whats is the mechanics here ?

Thanks!

**Comment by kdgutier** [comment]
There is an example of the 'unique_id' and 'x' variables in the README.
https://github.com/kdgutier/esrnn_torch
The 'unique_id' identifies the univariate time series from your panel data. While the the 'x' categorical variable is a static variable (one hot encoded within the model) that shows a single discrete characteristic of the time series, that is constant over time.
