### ISSUE TITLE
application for time series data with trend 

### ISSUE THREAD

**Issue by ramdhan1989** [kdgutier/esrnn_torch#26]
Hi, I am trying to use this package for air passenger dataset the result as follow :
![image](https://user-images.githubusercontent.com/41245856/104146078-fd823e00-53fb-11eb-8be2-d478b75349de.png)

is it good to use this package for this typical dataset (with seasonal and trend) ?

my model is look like this : 
`model = ESRNN(max_epochs=250, freq_of_test=5, batch_size=1, learning_rate=1e-3,
              per_series_lr_multip=0.8, lr_scheduler_step_size=10,
              lr_decay=0.1, gradient_clipping_threshold=50,
              rnn_weight_decay=0.0, level_variability_penalty=100,
              testing_percentile=0, training_percentile=100,
              ensemble=False, max_periods=25, seasonality=[12],
              input_size=12, output_size=40,
              cell_type='LSTM', state_hsize=40,
              dilations=[[1], [6]], add_nl_layer=False,
              random_seed=1, device='cuda')`

Is there any advice to tune the model in order to get good result ?

thank you

**Comment by kdgutier** [comment]
If there is a clear seasonality for example in your case a seasonality of [12] is reasonable. I recommend you to use the hyperopt library for hyperparameter selection (https://anaconda.org/conda-forge/hyperopt). Good luck!
