### ISSUE TITLE
Why is numpy==1.16.1 the only numpy version compatible with ESRNN?

### ISSUE THREAD

**Issue by michellemorales** [kdgutier/esrnn_torch#28]
Hi there,

I am working on building a forecasting ensemble pipeline that leverages a few different open source forecasting models, ESRNN, Keras, FBprophet, etc.

However, ESRNN is the only one that has an exact numpy version requirement, which is an older version than the rest of the libraries require. I am wondering why this is the only numpy version compatible with the library? It makes it impossible to ensemble it with any other library.

**Comment by AzulGarza** [comment]
Hi @michellemorales,

The [latest version](https://pypi.org/project/ESRNN/) does not have this limitation.

Thank you!
