### ISSUE TITLE
Allow for more covariates / features

### ISSUE THREAD

**Issue by StatMixedML** [kdgutier/esrnn_torch#33]
Thanks for making the model available!

Right now, as I see it, the RNN part of the model allows for one feature only. Would it be possible for you to extend the architecture to allow for an arbitrary number of features?

Many thanks!

**Comment by AzulGarza** [comment]
Hi! We've released a new library with new features, new models, and the possibility of setting more than one exogenous variable (temporal or static). The new library includes the ESRNN model.

https://github.com/Nixtla/nixtlats

Thanks!
