### ISSUE TITLE
ES-RNN for long sequence time series forecasting? 

### ISSUE THREAD

**Issue by puzzlecollector** [kdgutier/esrnn_torch#34]
@kdgutier 

I have a question - would ES-RNN perform well for long sequence time series forecasting in your opinion? So let's say the input is 4000 time steps and we need to predict the next 2000 time steps.

**Comment by kdgutier** [comment]
Hi @puzzlecollector,
It is an interesting question we have a workshop paper on the topic: https://arxiv.org/abs/2106.05860
We believe that the Holt-Winters seasonalities suffer from drifts in cases where the time series frequencies are not "fixed".
Additionally we have a pull request in this library: https://github.com/Nixtla/nixtlats/pull/80
 that will make the DMIDAS model available, it would be interesting for us if you try it and tell us how it went.
