### ISSUE TITLE
Hourly results typo in the results table in readme? 

### ISSUE THREAD

**Issue by jgerlach93** [kdgutier/esrnn_torch#37]
I noticed your implementation performs similar / better than the original implementation of smyl in all cases, but hourly data. In the table "current results", it is stated 0.615 vs 0.92. Could it be 0.915, instead? Otherwise, do you have an explanation for where that huge difference in performance comes from? 
Best, JC

**Comment by kdgutier** [comment]
Surprisingly the ES-RNN torch implementation was doing particularly well on hourly data.
We did not dig too much deeper on the issue I have not touched this model for some time. 
We included the ES-RNN in this new library/project https://github.com/Nixtla/neuralforecast.

**Comment by jgerlach93** [comment]
thanks much!
