### ISSUE TITLE
how to use continuous exogenous variable in the future for forecasting problem

### ISSUE THREAD

**Issue by ramdhan1989** [kdgutier/esrnn_torch#40]
Hi,
I need to forecast a target variable and I have two time series variable as continuous exog variables that can be used to forecast target series for multistep ahead. I can access the future values of exog variable and for production purpose I would like to simulate the impact of exog variable in the future to the forecasted target. So, I need to use exog at time t+1 to forecast target at time t+1 and so on.  can I do that? 

thank you

**Comment by kdgutier** [comment]
Hi @ramdhan1989,

I pointed you in the [NeuralForecast library](https://github.com/Nixtla/neuralforecast/) to N-BEATSx.
For the moment we have not worked throughly in the ES-RNNx model, I would advice against it until proven.
