### ISSUE TITLE
NAN for evaluation metrics

### ISSUE THREAD

**Issue by FangSimon** [kdgutier/esrnn_torch#6]
Hi there,

I am running into a similar problem as reported in a previous issue. While I do get a value for training loss and testing loss, I get a nan for my evaluation metrics: sMAPE, MASE and OWA, when I am fitting the model. The response below is when I am fitting the model with weekly data:

```
Infered frequency: W-SUN
=============== Training ESRNN ===============

========= Epoch 0 finished =========
Training time: 12.04543
Training loss (50 prc): 0.49441
Testing loss (50 prc): 0.02670
OWA: nan
SMAPE: nan
MASE: nan

```
I have checked and there are no zeroes in the first ds. What could be causing the problem?

**Comment by kdgutier** [comment]
Hi Fang, when that happened to me the most common cause is a mismatch between the horizons of the forecast and your test series.

**Comment by FangSimon** [comment]
Hi Kin, 
Thanks for the comment. I think one of the reasons was the seasonality. It is solved now! Thanks for developing this open-source library.
