### ISSUE TITLE
Monthly M3 Implementation of ESRNN

### ISSUE THREAD

**Issue by FangSimon** [kdgutier/esrnn_torch#7]
Hi there, 

Thanks a lot for the great implementation. I am trying to fit the monthly M3 data, but the model does not seem to be training. My data looks as follows:

![image](https://user-images.githubusercontent.com/22152704/84643778-969cb500-aefe-11ea-8199-3aa0d4e2f0fe.png)

![image](https://user-images.githubusercontent.com/22152704/84643808-9ef4f000-aefe-11ea-9643-670523c5ee3a.png)

![image](https://user-images.githubusercontent.com/22152704/84643817-a3b9a400-aefe-11ea-9e9a-5aa0771aedb4.png)

![image](https://user-images.githubusercontent.com/22152704/84643831-a87e5800-aefe-11ea-9fc6-17e582c2cf54.png)

Note that the y_hat_naive2 is in fact just the simple naive. 

When, I fit the model, I get the following: 

![image](https://user-images.githubusercontent.com/22152704/84644058-eed3b700-aefe-11ea-87c4-121f97f24e6f.png)

In an earlier issue, it has been mentioned that it could possibly be a mismatch in forecasting horizon, but after playing around with it, I don't see any improvement. Below, you can find a link to the colab notebook so you can reproduce it. 

https://colab.research.google.com/drive/1rFz5SskOqKuaxn3ijZUJwIPBqDGy7AK1?usp=sharing

Thanks a lot! 

Simon

**Comment by chendiva** [comment]
I have the same issue, have you solved it?

**Comment by FangSimon** [comment]
No I unfortunately, I have not solved it.

**Comment by FedericoGarza** [comment]
Hi!

We reviewed the colab notebook and made a few small changes to resolve the issue. In particular, we believe the following points will be useful for you:

- Check that the frequencies of the datasets (X_train_df, y_train_df, X_test_df, y_test_df) are all the same. With this verified, the ESRNN argument `frequency = None` can be used; this argument will automatically detect the frequency of the time series and use it to generate the predictions.
- Check the `output_size` argument. This argument determines the number of predictions that will be generated per time series. If this number is less than the size of the time series in the test set, the remaining values will be set to `NA`, so the OWA will be `NA`.

Thanks for your comments!

[Reviewed colab notebook](https://colab.research.google.com/drive/1Vdomwz9CJQDQBzW8NaDfeVw8KUxgWYay?usp=sharing)
