### ISSUE TITLE
ModuleNotFoundError: No module named 'ESRNN.m4_data'; 'ESRNN' is not a package

### ISSUE THREAD

**Issue by mgf31** [kdgutier/esrnn_torch#8]
Hello,

I've tried to install ESRNN via the instruction in this link: https://pypi.org/project/ESRNN/
which were: pip install ESRNN

However, when I try to run the follow code:

from ESRNN.m4_data import prepare_m4_data
from ESRNN.utils_evaluation import evaluate_prediction_owa

from ESRNN import ESRNN

I get the following error:

Traceback (most recent call last):
File "ESRNN.py", line 2, in
from ESRNN.m4_data import prepare_m4_data
File "C:\Users\mario\Documents\Python Benjamin\ESRNN.py", line 2, in
from ESRNN.m4_data import prepare_m4_data
ModuleNotFoundError: No module named 'ESRNN.m4_data'; 'ESRNN' is not a package

I've tried adding ESRNN as a path variable and still get the same error.

Could anyone please assist?

**Comment by kdgutier** [comment]
Hi Matt,

Let me see If I can help you
Can you create an .sh file with your setup and a jupyter notebook with what
you are trying to run?

Meanwhile, let me check the installation works for me
Greetings

**Comment by kdgutier** [comment]
Have you tried to download the github repository and run your tasks on top
of the ESRNN folder?
Here is the link https://github.com/kdgutier/esrnn_torch

I think there might be an issue with the Windows path creation and pip. (I
think you might have PC)
Hope this helps.

**Comment by kdgutier** [comment]
Also your problem sounds like a PATH problem
The way I run the code in Mac is:

On top of the ESRNN folder
PYTHONPATH=. python src/hyperpar_tunning_m4.py --id_min 0 --id_max 25
--dataset 'Daily' --gpu_id 0

Again hope this helps you

**Comment by kdgutier** [comment]
Another possible problem you might be facing is that the pip installation
was not done in the correct python environment.
If you are doing this with conda, make sure to "conda activate" before the
pip install.

**Comment by kdgutier** [comment]
1) Check that the pip installation is done in the correct python environment, if you are doing this with conda try "conda activate your_environment" before the pip install.
2) Other possible solution is giving the console the python path when running the code
PYTHONPATH=. python src/hyperpar_tunning_m4.py --id_min 0 --id_max 25 --dataset 'Daily' --gpu_id 0
